/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-06-19 06:37:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Schedule_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<FORM action=\"\" method=\"post\">\r\n");
      out.write("Course Name: <INPUT type=\"text\" name=\"title\" size=\"35\"><BR>\r\n");
      out.write("Course Time: \r\n");
      out.write("Sun<INPUT type=\"checkbox\" name=\"day\" value=\"sun\"> \r\n");
      out.write("Mon<INPUT type=\"checkbox\" name=\"day\" value=\"mon\"> \r\n");
      out.write("Tue<INPUT type=\"checkbox\" name=\"day\" value=\"tue\"> \r\n");
      out.write("Wed<INPUT type=\"checkbox\" name=\"day\" value=\"wed\"> \r\n");
      out.write("Thu<INPUT type=\"checkbox\" name=\"day\" value=\"thu\"> \r\n");
      out.write("Fri<INPUT type=\"checkbox\" name=\"day\" value=\"fri\"> \r\n");
      out.write("Sat<INPUT type=\"checkbox\" name=\"day\" value=\"sat\"> \r\n");
      out.write("<SELECT name=\"starttime\">\r\n");
      out.write("<OPTION value=\"8\">8:00am</OPTION>\r\n");
      out.write("<OPTION value=\"9\">9:00am</OPTION>\r\n");
      out.write("<OPTION value=\"10\">10:00am</OPTION>\r\n");
      out.write("<OPTION value=\"11\">11:00am</OPTION>\r\n");
      out.write("<OPTION value=\"12\">12:00pm</OPTION>\r\n");
      out.write("<OPTION value=\"13\">1:00pm</OPTION>\r\n");
      out.write("<OPTION value=\"14\">2:00pm</OPTION>\r\n");
      out.write("<OPTION value=\"15\">3:00pm</OPTION>\r\n");
      out.write("<OPTION value=\"16\">4:00pm</OPTION>\r\n");
      out.write("<OPTION value=\"17\">5:00pm</OPTION>\r\n");
      out.write("<OPTION value=\"18\">6:00pm</OPTION>\r\n");
      out.write("<OPTION value=\"19\">7:00pm</OPTION>\r\n");
      out.write("<OPTION value=\"20\">8:00pm</OPTION>\r\n");
      out.write("<OPTION value=\"21\">9:00pm</OPTION>\r\n");
      out.write("</SELECT> \r\n");
      out.write("to \r\n");
      out.write("<SELECT name=\"endtime\">\r\n");
      out.write("<OPTION value=\"9\">9:00am</OPTION>\r\n");
      out.write("<OPTION value=\"10\">10:00am</OPTION>\r\n");
      out.write("<OPTION value=\"11\">11:00am</OPTION>\r\n");
      out.write("<OPTION value=\"12\">12:00pm</OPTION>\r\n");
      out.write("<OPTION value=\"13\">1:00pm</OPTION>\r\n");
      out.write("<OPTION value=\"14\">2:00pm</OPTION>\r\n");
      out.write("<OPTION value=\"15\">3:00pm</OPTION>\r\n");
      out.write("<OPTION value=\"16\">4:00pm</OPTION>\r\n");
      out.write("<OPTION value=\"17\">5:00pm</OPTION>\r\n");
      out.write("<OPTION value=\"18\">6:00pm</OPTION>\r\n");
      out.write("<OPTION value=\"19\">7:00pm</OPTION>\r\n");
      out.write("<OPTION value=\"20\">8:00pm</OPTION>\r\n");
      out.write("<OPTION value=\"21\">9:00pm</OPTION>\r\n");
      out.write("<OPTION value=\"22\">10:00pm</OPTION>\r\n");
      out.write("</SELECT>\r\n");
      out.write("<BR>\r\n");
      out.write("<BR>\r\n");
      out.write("<INPUT type=\"submit\" name=\"Submit\" value=\"Add Course\">\r\n");
      out.write("</FORM>\r\n");
      out.write("<FORM action=\"/SchoolSchedule/Schedule\" method=\"post\"></FORM>\r\n");
      out.write("\r\n");
      out.write("<TABLE border=\"1\" cellspacing=\"0\">\r\n");
      out.write("<TBODY>\r\n");
      out.write("<TR>\r\n");
      out.write("<TH align=\"center\" valign=\"middle\" width=\"80\"></TH>\r\n");
      out.write("<TH align=\"center\" valign=\"middle\" width=\"100\">Sunday</TH>\r\n");
      out.write("<TH align=\"center\" valign=\"middle\">Monday</TH>\r\n");
      out.write("<TH align=\"center\" valign=\"middle\">Tuesday</TH>\r\n");
      out.write("<TH align=\"center\" valign=\"middle\">Wednesday</TH>\r\n");
      out.write("<TH align=\"center\" valign=\"middle\">Thursday</TH>\r\n");
      out.write("<TH align=\"center\" valign=\"middle\">Friday</TH>\r\n");
      out.write("<TH align=\"center\" valign=\"middle\">Saturday</TH>\r\n");
      out.write("</TR>\r\n");
      out.write("<c:forEach begin=\"8\" end=\"21\" step=\"1\" var=\"time\">\r\n");
      out.write("<TR>\r\n");
      out.write("<TD align=\"center\" valign=\"middle\" width=\"80\">\r\n");
      out.write("<c:choose>\r\n");
      out.write("<c:when test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time == 12}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<c:out value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />:00pm\r\n");
      out.write("</c:when>\r\n");
      out.write("<c:when test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time > 12}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<c:out value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time - 12}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />:00pm\r\n");
      out.write("</c:when>\r\n");
      out.write("<c:otherwise>\r\n");
      out.write("<c:out value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />:00am\r\n");
      out.write("</c:otherwise>\r\n");
      out.write("</c:choose></TD>\r\n");
      out.write("<c:forEach begin=\"0\" end=\"6\" step=\"1\" var=\"day\">\r\n");
      out.write("<TD align=\"center\" valign=\"middle\" width=\"100\">\r\n");
      out.write("<c:forEach items=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${schoolschedule.classes}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" var=\"clazz\">\r\n");
      out.write("<c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${clazz.startTime <= time \r\n&& clazz.endTime > time \r\n&& clazz.day == day}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<c:out value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${clazz.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("</c:if>\r\n");
      out.write("</c:forEach>\r\n");
      out.write("</TD>\r\n");
      out.write("</c:forEach>\r\n");
      out.write("</TR>\r\n");
      out.write("</c:forEach>\r\n");
      out.write("</TBODY>\r\n");
      out.write("</TABLE>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
